import { ipcMain } from 'electron'
import type { Controller } from './controller'

export function registerIpc(controller: Controller): void {
  ipcMain.handle('status:get', () => controller.getStatus())
  ipcMain.handle('server:start', () => controller.start())
  ipcMain.handle('server:stop', () => controller.stop())
  ipcMain.handle('server:restart', () => controller.restart())
  ipcMain.handle('dsh:install', () => controller.install())
  ipcMain.handle('dsh:update', (_e, version?: string) => controller.update(version))
  ipcMain.handle('dsh:versions', () => controller.listVersions())
  ipcMain.handle('settings:get', () => controller.getSettings())
  ipcMain.handle('settings:set', (_e, patch) => controller.setSettings(patch))
  ipcMain.handle('logs:get', () => controller.getLogs())
  ipcMain.handle('app:openWebUI', () => controller.openWebUI())
  ipcMain.handle('app:openDashboard', () => controller.openDashboard())
  ipcMain.handle('app:openDshHome', () => controller.openDshHome())
  ipcMain.handle('app:openPluginsDir', () => controller.openPluginsDir())
  ipcMain.handle('app:checkUpdate', () => controller.checkAppUpdate())
  ipcMain.handle('app:downloadUpdate', () => controller.downloadAppUpdate())
  ipcMain.handle('app:installUpdate', () => controller.installAppUpdate())
  ipcMain.handle('plugins:list', () => controller.listPlugins())
  ipcMain.handle('plugins:search', (_e, query: string, sort?: string, source?: string) => controller.searchPlugins(query, sort, source))
  ipcMain.handle('plugins:install', (_e, name: string, source?: string) => controller.installPlugin(name, source))
  ipcMain.handle('plugins:uninstall', (_e, name: string) => controller.uninstallPlugin(name))
  ipcMain.handle('app:pickBackgroundImage', () => controller.pickBackgroundImage())
  ipcMain.handle('app:openExternal', (_e, url: string) => controller.openExternal(url))
  ipcMain.handle('plugins:backups', () => controller.listBackups())
  ipcMain.handle('plugins:restoreBackup', (_e, name: string) => controller.restoreBackup(name))
  ipcMain.handle('plugins:deleteBackup', (_e, name: string) => controller.deleteBackup(name))
  // v0.2.0：WSL 后端
  ipcMain.handle('backend:info', () => controller.backendInfo())
  ipcMain.handle('backend:setMode', (_e, mode: 'local' | 'wsl') => controller.backendSetMode(mode))
  ipcMain.handle('backend:setDistro', (_e, distro: string) => controller.backendSetDistro(distro))
  ipcMain.handle('backend:setup', (_e, distro: string) => controller.backendSetup(distro))
  ipcMain.handle('backend:installDistro', (_e, name: string) => controller.backendInstallDistro(name))
  ipcMain.handle('backend:diagnose', () => controller.backendDiagnose())
  ipcMain.handle('backend:forceCleanup', () => controller.backendForceCleanup())
  // v0.2.0：文件桥
  ipcMain.handle('fsb:list', (_e, side: 'win' | 'wsl', path: string) => controller.fsbList(side, path))
  ipcMain.handle('fsb:transfer', (_e, jobs: Parameters<Controller['fsbTransfer']>[0]) => controller.fsbTransfer(jobs))
  ipcMain.handle('fsb:cancel', (_e, id: string) => controller.fsbCancel(id))
  ipcMain.handle('fsb:remove', (_e, side: 'win' | 'wsl', path: string) => controller.fsbRemove(side, path))
  ipcMain.handle('fsb:rename', (_e, side: 'win' | 'wsl', path: string, newName: string) => controller.fsbRename(side, path, newName))
  ipcMain.handle('fsb:mkdir', (_e, side: 'win' | 'wsl', path: string) => controller.fsbMkdir(side, path))
  ipcMain.handle('fsb:translate', (_e, path: string) => controller.fsbTranslate(path))
  ipcMain.handle('fsb:open', (_e, side: 'win' | 'wsl', path: string, terminal?: boolean) => controller.fsbOpen(side, path, terminal))
  ipcMain.handle('app:quit', () => controller.quit())
}
